/**
 * URL state — sync app state to/from the URL.
 *
 * The URL has two parts:
 *
 *   1. The path identifies *what* you're looking at — the kind of page.
 *      Pretty paths are statically generated by `scripts/generate_pages.py`
 *      so search engines see real HTML before any JS runs.
 *
 *        /                  Homepage (GPS / location-search experience)
 *        /<city>/           City landing page (e.g. /norwich/)
 *        /pub/<slug>/       Per-pub page (PR #2 — served by a Pages Function)
 *
 *   2. Query params layer time/date scrubbing on top of any route, plus
 *      lat/lng for sharing GPS coordinates from the homepage:
 *
 *        ?t=720             Time in minutes from midnight (default: now)
 *        ?d=2026-04-15      Date (default: today; omitted when today)
 *        ?lat=52.63&lng=1.3 GPS coords (only meaningful on `/`)
 *
 * Internal navigation that changes the path uses pushState so the browser
 * back button works. Time/date scrubbing on the same path uses replaceState
 * to avoid flooding history during slider drags.
 */

import { state } from "./state";

// ── Types ────────────────────────────────────────────────────────────

export type Route =
  | { kind: "home"; lat?: number; lng?: number }
  | { kind: "city"; citySlug: string }
  | { kind: "pub"; pubSlug: string };

export interface URLState {
  route: Route;
  time?: number;
  date?: Date;
}

// ── Read ─────────────────────────────────────────────────────────────

/** Parse the current `window.location` into a typed URL state. */
export function readURL(): URLState {
  const params = new URLSearchParams(window.location.search);
  const result: URLState = { route: parsePath(window.location.pathname) };

  // Homepage may carry GPS coords for sharing.
  if (result.route.kind === "home") {
    const lat = params.get("lat");
    const lng = params.get("lng");
    if (lat && lng) {
      const latNum = parseFloat(lat);
      const lngNum = parseFloat(lng);
      if (Number.isFinite(latNum) && Number.isFinite(lngNum)) {
        result.route = { kind: "home", lat: latNum, lng: lngNum };
      }
    }
  }

  const t = params.get("t");
  if (t) {
    const time = parseInt(t, 10);
    if (Number.isFinite(time)) result.time = time;
  }

  const d = params.get("d");
  if (d) {
    const m = d.match(/^(\d{4})-(\d{2})-(\d{2})$/);
    if (m && m[1] && m[2] && m[3]) {
      const date = new Date(parseInt(m[1], 10), parseInt(m[2], 10) - 1, parseInt(m[3], 10));
      if (!Number.isNaN(date.getTime())) result.date = date;
    }
  }

  return result;
}

/** Pure path → route parser. Exported for testing and for popstate handling. */
export function parsePath(path: string): Route {
  const segments = path
    .replace(/^\/+|\/+$/g, "")
    .split("/")
    .filter(Boolean);
  if (segments.length === 0) return { kind: "home" };
  if (segments[0] === "pub" && segments[1]) {
    return { kind: "pub", pubSlug: segments[1] };
  }
  // Single segment → city slug. Multi-segment paths fall through to home
  // (PR #1 only generates flat city pages; theme pages come in PR #3).
  if (segments.length === 1 && segments[0]) {
    return { kind: "city", citySlug: segments[0] };
  }
  return { kind: "home" };
}

// ── Write ────────────────────────────────────────────────────────────

/**
 * The current "base path" — the route the page was loaded on. Time/date
 * scrubbing and location updates write back to this path so the URL stays
 * coherent. main.ts calls setBasePath() once during init based on the
 * meta tags or the parsed URL.
 */
let basePath = "/";

export function setBasePath(path: string): void {
  basePath = path;
}

export function getBasePath(): string {
  return basePath;
}

/**
 * Whether the user has actively interacted with the time slider on this
 * page load. Until they do, writeURL() suppresses `?t=` so a fresh
 * landing-page URL stays clean (no `/norwich/?t=727` cruft right after
 * arriving from a Google result). main.ts also flips this flag when the
 * incoming URL already had a `?t=` param so reloading a shared URL
 * preserves it.
 */
let timeIsUserDriven = false;

export function markTimeUserDriven(): void {
  timeIsUserDriven = true;
}

export function clearTimeUserDriven(): void {
  timeIsUserDriven = false;
}

/**
 * Compute the path the URL should currently have, based on app state.
 *
 * If a pub is selected and has a slug → /pub/<slug>/
 * Otherwise → the base path (homepage / or /<city>/)
 *
 * This is the single source of truth for "what URL should I have right
 * now" — both writeURL() and the navigation logic in main.ts route through
 * it so the URL bar always agrees with what the user is looking at.
 */
function pathFromState(): string {
  const sel = state.pubs.find((p) => p.id === state.selectedPubId);
  if (sel?.slug) return `/pub/${sel.slug}/`;
  return basePath;
}

let suppressWrite = false;

/**
 * Run a function with URL writes suppressed. Used to prevent recursion when
 * programmatic state changes (auto-selecting closest pub on location change)
 * would otherwise trigger redundant writeURL calls.
 */
export function withSuppressedWrites<T>(fn: () => T): T {
  const prev = suppressWrite;
  suppressWrite = true;
  try {
    return fn();
  } finally {
    suppressWrite = prev;
  }
}

/**
 * Write current state to the URL.
 *
 * - Path changes (selecting a pub, navigating to a city) use pushState so
 *   the browser back button works.
 * - Query-only changes (time scrubbing, GPS coord sharing) use replaceState
 *   so we don't flood history during slider drags.
 */
export function writeURL(): void {
  if (suppressWrite) return;

  const path = pathFromState();
  const params = new URLSearchParams();

  // Time only when the user has actively scrubbed it (or had a `?t=` in the
  // incoming URL). Idle landing-page URLs stay clean.
  if (timeIsUserDriven) {
    params.set("t", String(Math.round(state.timeMins)));
  }

  // Date only when not today.
  const now = new Date();
  if (
    state.date.getFullYear() !== now.getFullYear() ||
    state.date.getMonth() !== now.getMonth() ||
    state.date.getDate() !== now.getDate()
  ) {
    const y = state.date.getFullYear();
    const m = String(state.date.getMonth() + 1).padStart(2, "0");
    const d = String(state.date.getDate()).padStart(2, "0");
    params.set("d", `${y}-${m}-${d}`);
  }

  // Coords only on the homepage when there's no city / pub context.
  if (path === "/" && state.userLat != null && state.userLng != null) {
    params.set("lat", state.userLat.toFixed(4));
    params.set("lng", state.userLng.toFixed(4));
  }

  const search = params.toString();
  const target = search ? `${path}?${search}` : path;
  const currentTarget = window.location.pathname + (window.location.search || "");
  if (target === currentTarget) return;

  // pushState if the path itself changed (real navigation); replaceState if
  // only query params changed (in-place update).
  const pathChanged = window.location.pathname !== path;
  if (pathChanged) {
    window.history.pushState(null, "", target);
  } else {
    window.history.replaceState(null, "", target);
  }
}

/** Debounced URL update — for time-slider scrubbing. */
let writeTimer: number | null = null;

export function writeURLDebounced(): void {
  if (writeTimer != null) clearTimeout(writeTimer);
  writeTimer = window.setTimeout(() => {
    writeTimer = null;
    writeURL();
  }, 300);
}

// ── popstate (browser back/forward) ──────────────────────────────────

let popstateHandler: ((urlState: URLState) => void) | null = null;

/** Register a callback fired on browser back/forward navigation. */
export function onPopState(handler: (urlState: URLState) => void): void {
  popstateHandler = handler;
}

if (typeof window !== "undefined") {
  window.addEventListener("popstate", () => {
    if (popstateHandler) popstateHandler(readURL());
  });
}

// ── Friendly location label (in-memory, used by UI button) ──────────

let currentLocationLabel = "";

export function setLocationQuery(q: string): void {
  currentLocationLabel = q;
}

export function getLocationQuery(): string {
  return currentLocationLabel;
}

// ── Document head sync ──────────────────────────────────────────────

/**
 * Update document.title and the canonical link to match the current page.
 * Static HTML already has the right values on first paint; this only
 * matters during in-app navigation (PR #2 onwards). Kept here so url.ts
 * is the single owner of URL ↔ head consistency.
 */
export function syncDocumentHead(opts: { title?: string; canonicalPath?: string }): void {
  if (opts.title !== undefined) document.title = opts.title;
  if (opts.canonicalPath !== undefined) {
    let link = document.querySelector('link[rel="canonical"]') as HTMLLinkElement | null;
    if (!link) {
      link = document.createElement("link");
      link.rel = "canonical";
      document.head.appendChild(link);
    }
    link.href = `https://sunny-pint.co.uk${opts.canonicalPath}`;
  }
}
